import type { BackendRatioDefinition } from '../../types/ratio.js';

/**
 * Backend Ratio Registry (Session R1) — the authoritative business
 * definition for each of the 21 primary ratios named in
 * docs/CALL_CENTRE_RATIO_EXPLORER_UX_AND_RATIO_REGISTRY_v1.1.docx §9.
 *
 * This file is the ONLY place a ratio's numerator/denominator/eligibility
 * is described. src/server/analytics/ratioService.ts consumes it;
 * api/analytics/metrics.ts's `resource=ratios` branch calls that service.
 * React components never import this file.
 *
 * Availability is reconciled against the ACTUAL current repository/API,
 * not copied blindly from the spec doc — see the comment on each entry
 * that differs from (or confirms) the spec's own classification.
 *
 * Confirmed real, currently-available source fields (src/types/api/calls.ts
 * CallDataEntryDto / AnalyticsMetricsFields):
 *   fcr (boolean), outcome ('resolved'|'escalated'), escalation_trigger,
 *   was_authenticated (boolean|null), intent_accuracy (0-100 — this is
 *   classifier confidence, NOT measured accuracy against ground truth,
 *   see the intent-accuracy entry below), sentiment/sentiment_score.
 *   AnalyticsMetricsFields (GET /api/v1/analytics/metrics, GLOBAL
 *   aggregate only, no agent/campaign/intent dimension): fcr_rate,
 *   avg_aht_seconds, escalation_rate, resolved_count, escalated_count,
 *   avg_intent_accuracy.
 * No campaign_targets attempt-to-connection field, no QA/survey/cost
 * telemetry, no interaction_events table exist in this repository today.
 */
export const BACKEND_RATIO_REGISTRY: Record<string, BackendRatioDefinition> = {
  contact_rate: {
    id: 'contact_rate',
    family: 'operations',
    numeratorDescription: 'Outbound campaign executions that connected to the customer',
    denominatorDescription: 'Outbound campaign executions attempted',
    eligibilityNote: 'Requires a "connected" signal distinct from "triggered" on campaign_executions — not currently recorded.',
    supportedDimensions: ['campaign', 'agent', 'time', 'domain'],
    driverDimension: null,
    evidence: { transcript: true, recording: true, metadata: true },
    availability: 'backend_gap',
    unavailableReason: 'Backend telemetry required — campaign_executions has no "connected" outcome distinct from dial attempt.',
  },
  completion_rate: {
    id: 'completion_rate',
    family: 'operations',
    numeratorDescription: 'Interactions with stage=completed',
    denominatorDescription: 'Interactions answered/connected',
    eligibilityNote: 'Call-data "stage" field distinguishes completed from in-progress; a connected-but-abandoned population is not separately flagged.',
    supportedDimensions: ['intent', 'agent', 'campaign', 'time'],
    driverDimension: null,
    evidence: { transcript: true, recording: true, metadata: true },
    availability: 'derived',
    unavailableReason: null,
  },
  resolution_rate: {
    id: 'resolution_rate',
    family: 'operations',
    numeratorDescription: 'Interactions with outcome=resolved',
    denominatorDescription: 'Completed interactions with a known outcome',
    eligibilityNote: 'Call-data outcome field is a real, confirmed source (resolved/escalated).',
    supportedDimensions: ['intent', 'agent', 'campaign', 'domain', 'outcome'],
    driverDimension: 'escalation_reason',
    evidence: { transcript: true, recording: true, metadata: true },
    availability: 'direct',
    unavailableReason: null,
  },
  fcr: {
    id: 'fcr',
    family: 'operations',
    numeratorDescription: 'Interactions with fcr=true',
    denominatorDescription: 'Eligible completed interactions',
    eligibilityNote: 'Global aggregate already exposed as fcr_rate on GET /api/v1/analytics/metrics; per-call fcr boolean also confirmed on call-data.',
    supportedDimensions: ['intent', 'agent', 'campaign', 'domain'],
    driverDimension: null,
    evidence: { transcript: true, recording: true, metadata: true },
    availability: 'direct',
    unavailableReason: null,
  },
  escalation_rate: {
    id: 'escalation_rate',
    family: 'operations',
    numeratorDescription: 'Interactions with outcome=escalated',
    denominatorDescription: 'Handled interactions',
    eligibilityNote: 'Global aggregate already exposed as escalation_rate on GET /api/v1/analytics/metrics; escalation_trigger available for driver breakdown.',
    supportedDimensions: ['intent', 'agent', 'campaign', 'time'],
    driverDimension: 'escalation_reason',
    evidence: { transcript: true, recording: true, metadata: true },
    availability: 'direct',
    unavailableReason: null,
  },
  repeat_contact_rate: {
    id: 'repeat_contact_rate',
    family: 'operations',
    numeratorDescription: 'Same-customer contacts for the same issue within a follow-up window',
    denominatorDescription: 'Eligible resolved/closed interactions',
    eligibilityNote: 'Requires linking repeat contacts by customer identity + issue/intent match over time — Customer 360 has customer identity, but no "same issue" linkage exists yet.',
    supportedDimensions: ['intent', 'segment', 'time'],
    driverDimension: null,
    evidence: { transcript: true, recording: true, metadata: true },
    availability: 'backend_gap',
    unavailableReason: 'Backend telemetry required — no same-issue repeat-contact linkage exists yet.',
  },
  aht: {
    id: 'aht',
    family: 'operations',
    numeratorDescription: 'Sum of handling duration across handled interactions',
    denominatorDescription: 'Count of handled interactions',
    eligibilityNote: 'Global aggregate already exposed as avg_aht_seconds on GET /api/v1/analytics/metrics.',
    supportedDimensions: ['intent', 'agent', 'campaign', 'outcome', 'time'],
    driverDimension: null,
    evidence: { transcript: true, recording: true, metadata: true },
    availability: 'direct',
    unavailableReason: null,
  },
  successful_resolution_time: {
    id: 'successful_resolution_time',
    family: 'operations',
    numeratorDescription: 'Sum of duration across resolved-outcome interactions',
    denominatorDescription: 'Count of resolved-outcome interactions',
    eligibilityNote: 'Computable by filtering call-data duration_seconds to outcome=resolved — not currently exposed as a pre-aggregated field.',
    supportedDimensions: ['intent', 'agent', 'campaign', 'time'],
    driverDimension: null,
    evidence: { transcript: true, recording: true, metadata: true },
    availability: 'derived',
    unavailableReason: null,
  },
  autonomous_resolution_rate: {
    id: 'autonomous_resolution_rate',
    family: 'intelligence',
    numeratorDescription: 'AI-only resolved interactions (no human transfer)',
    denominatorDescription: 'Eligible AI-handled interactions',
    eligibilityNote: 'No explicit "resolution mode" (AI-only vs. human-assisted) field exists on call-data.',
    supportedDimensions: ['intent', 'agent', 'campaign', 'domain'],
    driverDimension: 'escalation_reason',
    evidence: { transcript: true, recording: true, metadata: true },
    availability: 'backend_gap',
    unavailableReason: 'Backend telemetry required — no explicit AI-only-resolution flag exists yet.',
  },
  authentication_success_rate: {
    id: 'authentication_success_rate',
    family: 'intelligence',
    numeratorDescription: 'Interactions with was_authenticated=true',
    denominatorDescription: 'Interactions where authentication was attempted',
    eligibilityNote: 'was_authenticated is a real per-call boolean, but there is no separate "attempted" flag distinct from "succeeded" — an attempted-but-failed authentication cannot currently be distinguished from "not attempted".',
    supportedDimensions: ['intent', 'agent', 'campaign', 'domain'],
    driverDimension: null,
    evidence: { transcript: true, recording: true, metadata: true },
    availability: 'partial',
    unavailableReason: 'A real was_authenticated flag exists, but no distinct "attempted" signal exists to form an honest denominator yet.',
  },
  intent_accuracy: {
    id: 'intent_accuracy',
    family: 'intelligence',
    numeratorDescription: 'Correct intent classifications against evaluated ground truth',
    denominatorDescription: 'Evaluated intent classifications',
    eligibilityNote: 'The only existing field, intent_accuracy on call-data, is the model\'s own classifier confidence score — not a measured accuracy against a human-verified ground-truth label. Presenting it as "accuracy" would violate the explicit truthfulness rule against showing model confidence as measured accuracy.',
    supportedDimensions: ['intent', 'agent', 'domain', 'time'],
    driverDimension: null,
    evidence: { transcript: true, metadata: true },
    availability: 'backend_gap',
    unavailableReason: 'Backend telemetry required — the existing intent_accuracy field is classifier confidence, not measured accuracy against ground truth.',
  },
  tool_success_rate: {
    id: 'tool_success_rate',
    family: 'intelligence',
    numeratorDescription: 'Successful tool calls',
    denominatorDescription: 'Tool call attempts',
    eligibilityNote: 'No interaction_events / tool-call telemetry table exists in this repository.',
    supportedDimensions: ['tool', 'intent', 'agent', 'time'],
    driverDimension: 'tool',
    evidence: { ai_trace: true },
    availability: 'backend_gap',
    unavailableReason: 'Backend telemetry required — no tool-call event model exists yet.',
  },
  fallback_rate: {
    id: 'fallback_rate',
    family: 'intelligence',
    numeratorDescription: 'AI turns that fell back to a generic/handoff response',
    denominatorDescription: 'AI conversational turns',
    eligibilityNote: 'No turn-level fallback event telemetry exists in this repository.',
    supportedDimensions: ['intent', 'agent', 'time'],
    driverDimension: null,
    evidence: { ai_trace: true },
    availability: 'backend_gap',
    unavailableReason: 'Backend telemetry required — no turn-level fallback event exists yet.',
  },
  avoidable_escalation_rate: {
    id: 'avoidable_escalation_rate',
    family: 'intelligence',
    numeratorDescription: 'Escalations attributable to an AI failure or technical fault',
    denominatorDescription: 'All escalations',
    eligibilityNote: 'escalation_trigger is a real free-form field, but has no normalized taxonomy separating avoidable (AI/technical) from unavoidable (genuine complexity) causes.',
    supportedDimensions: ['intent', 'agent', 'tool'],
    driverDimension: 'escalation_reason',
    evidence: { transcript: true, recording: true, metadata: true },
    availability: 'partial',
    unavailableReason: 'A real escalation_trigger field exists, but lacks a normalized avoidable/unavoidable taxonomy for a production-grade split.',
  },
  qa_pass_rate: {
    id: 'qa_pass_rate',
    family: 'quality',
    numeratorDescription: 'Interactions meeting the QA pass threshold',
    denominatorDescription: 'Interactions with a completed QA review',
    eligibilityNote: 'QA Review exists as a workflow screen, but no persisted QA score/pass-fail record was found in the schema this session inspected.',
    supportedDimensions: ['agent', 'intent', 'campaign'],
    driverDimension: null,
    evidence: { qa: true, transcript: true },
    availability: 'backend_gap',
    unavailableReason: 'Backend telemetry required — no persisted QA pass/fail record exists yet.',
  },
  compliance_pass_rate: {
    id: 'compliance_pass_rate',
    family: 'quality',
    numeratorDescription: 'Interactions with zero critical compliance failures',
    denominatorDescription: 'Evaluated interactions',
    eligibilityNote: 'Same gap as QA Pass Rate — no persisted compliance rule-failure record exists.',
    supportedDimensions: ['agent', 'intent', 'domain'],
    driverDimension: null,
    evidence: { qa: true },
    availability: 'backend_gap',
    unavailableReason: 'Backend telemetry required — no persisted compliance evaluation record exists yet.',
  },
  csat: {
    id: 'csat',
    family: 'quality',
    numeratorDescription: 'Satisfied survey responses',
    denominatorDescription: 'Valid survey responses',
    eligibilityNote: 'No customer-satisfaction survey capture/storage exists in this repository.',
    supportedDimensions: ['agent', 'intent', 'campaign', 'time'],
    driverDimension: null,
    evidence: {},
    availability: 'backend_gap',
    unavailableReason: 'Backend telemetry required — no CSAT survey capture exists yet.',
  },
  nps: {
    id: 'nps',
    family: 'quality',
    numeratorDescription: '% promoters minus % detractors',
    denominatorDescription: 'Valid NPS survey responses',
    eligibilityNote: 'No NPS survey response capture exists (NPS Campaigns screen manages campaign delivery, not response persistence, as inspected this session).',
    supportedDimensions: ['campaign', 'agent', 'domain', 'time'],
    driverDimension: null,
    evidence: {},
    availability: 'backend_gap',
    unavailableReason: 'Backend telemetry required — no NPS response capture exists yet.',
  },
  business_outcome_success: {
    id: 'business_outcome_success',
    family: 'business',
    numeratorDescription: 'Interactions with a successful business outcome',
    denominatorDescription: 'Eligible interactions for the relevant business outcome type',
    eligibilityNote: 'No domain-neutral business-outcome model exists yet (campaign_results is campaign-specific, not a general interaction-level outcome model).',
    supportedDimensions: ['outcome', 'campaign', 'intent', 'segment'],
    driverDimension: null,
    evidence: { transcript: true, metadata: true },
    availability: 'backend_gap',
    unavailableReason: 'Backend telemetry required — no domain-neutral business-outcome model exists yet.',
  },
  conversion_rate: {
    id: 'conversion_rate',
    family: 'business',
    numeratorDescription: 'Conversions',
    denominatorDescription: 'Eligible contacts',
    eligibilityNote: 'No conversion-event capture exists outside campaign result-rule labels, which are operational classification, not a confirmed conversion event.',
    supportedDimensions: ['campaign', 'segment', 'agent', 'time'],
    driverDimension: null,
    evidence: { metadata: true },
    availability: 'backend_gap',
    unavailableReason: 'Backend telemetry required — no confirmed conversion-event capture exists yet.',
  },
  cost_per_resolution: {
    id: 'cost_per_resolution',
    family: 'business',
    numeratorDescription: 'Operating cost attributable to the period',
    denominatorDescription: 'Resolved interactions',
    eligibilityNote: 'No cost telemetry (per-call or per-minute pricing) exists anywhere in this repository.',
    supportedDimensions: ['domain', 'campaign', 'agent', 'intent'],
    driverDimension: null,
    evidence: {},
    availability: 'backend_gap',
    unavailableReason: 'Backend telemetry required — no cost telemetry exists yet.',
  },
};

export function getBackendRatioDefinition(ratioId: string): BackendRatioDefinition | null {
  return BACKEND_RATIO_REGISTRY[ratioId] ?? null;
}
